---

- name: Install ldap-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_items: [ 'libpam-ldap' ]

- name: Configure ldap
  template:
    src: 'etc/ldap/ldap.conf.j2'
    dest: '/etc/ldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
