---

- name: Install ldap-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_items: [ 'nslcd', 'libpam-ldap', 'ldap-utils' ]

- name: Configure ldap
  template:
    src: 'etc/ldap/ldap.conf.j2'
    dest: '/etc/ldap/ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure nslcd
  template:
    src: 'etc/nslcd.conf.j2'
    dest: '/etc/nslcd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: [ 'Restart nslcd' ]

- name: Configure PAM LDAP
  template:
    src: 'etc/pam_ldap.conf.j2'
    dest: '/etc/pam_ldap.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Configure PAM LDAP password
  template:
    src: 'etc/pam_ldap.secret.j2'
    dest: '/etc/pam_ldap.secret'
    owner: 'root'
    group: 'root'
    mode: '0600'
