---

- name: Install auth-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_items: auth_packages

- name: Create common system groups
  group:
    name: '{{ item }}'
    system: true
    state: 'present'
  with_items: auth_system_groups
  when: auth_system_groups is defined and auth_system_groups

- name: Configure security access
  template:
    src: 'etc/security/access.conf.j2'
    dest: '/etc/security/access.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
